#!/usr/bin/env bash
#creates a file for the process pid

#creating the file containing the pid
echo $$ > /var/run/myscript.pid

#trap the signals and define their behaviour
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/myscript.pid && exit 0" SIGQUIT SIGTERM

#Displays a mesage indefinitely
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
