#!/usr/bin/env bash
#Displays numbers from 1 to 100 and fizzbuzz for multiples of 3 or/and 5
number=1
while [[ number -le 100 ]]
do
	if (( number%3==0  && number%5==0 ));
	then
		echo "FizzBuzz"
	elif (( number%3==0 ));
	then
		echo "Fizz"
	elif (( number%5==0 ));
	then
		echo "Buzz"
	else
		echo "$number"
	fi
	number=$(( number+1 ))
done
