#!/usr/bin/env bash
#This script displays 'Best school' bt displays hi on the 9th iteration
iteration=0
while [ $iteration -lt 10 ]
do
    if [[ $iteration -eq 9 ]]
    then
    echo "Hi"
    fi
    echo "Best School"
    iteration=$((iteration + 1))
done
