#!/usr/bin/env bash
#This script displays 'Best school' bt displays hi on the 9th iteration
iteration=1
while [ $iteration -le 20 ]
do
   case $iteration in
	   5)
		   echo "bad luck from china"
		   ;;
	   10)
		   echo "bad luck from japan"
		   ;;
	   18)
		   echo "bad luck from Italy"
		   ;;
   esac
   echo "$iteration"
   iteration=$((iteration + 1))
done
